const CustomersActionTypes = {
    GET_DATA_AGENTS: "GET_DATA_AGENTS",
    GET_DATA_AGENTS_SUCCESS: "GET_DATA_AGENTS_SUCCESS",
    GET_DATA_AGENTS_FAILURE: "GET_DATA_AGENTS_FAILURE",
    GET_DATA_COMPANY: "GET_DATA_COMPANY",
    GET_DATA_COMPANY_SUCCESS: "GET_DATA_COMPANY_SUCCESS",
    GET_DATA_COMPANY_FAILURE: "GET_DATA_COMPANY_FAILURE",
  };
  
  export default CustomersActionTypes;
  